project:
  type: website
  output-dir: docs
website:
  title: "Zoe Bean"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/zbean17
      - icon: linkedin
        href: https://www.linkedin.com/in/zoe-bean170/
      - icon: envelope
        href: mailto:zoeannebean@gmail.com
  sidebar:
    style: docked
    contents: ["aboutMe.qmd", "resume.qmd"]
      
format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

